AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VPCCidr:
    Description: vpc Cider ip range
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '^(\d{1,3}\.){3}\d{1,3}\/\d{1,2}$'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

  PublicSubnetCidr:
    Description: Public Subnet ipv4 address range
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '^(\d{1,3}\.){3}\d{1,3}\/\d{1,2}$'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.


  PrivateDBSubnetCidr:
    Description: Private Subnet ipv4 for db cluster
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '^(\d{1,3}\.){3}\d{1,3}\/\d{1,2}$'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.


  PrivateSubnetCidr:
    Description: Private Subnet ipv4 address range
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '^(\d{1,3}\.){3}\d{1,3}\/\d{1,2}$'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

  AvailabilityZone1:
    Description: Primary availability zone, used for public and one private subnet
    Type: String

  AvailabilityZone2:
    Description: AZ used for the db cluster to provide constistancy
    Type: String


Resources:
  AngularVoteApp:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref AngularVoteApp
                - /*
      Bucket: !Ref AngularVoteApp
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidr
      EnableDnsHostnames: false
      EnableDnsSupport: false
      Tags:
        - Key: "BatchID"
          Value: "DevOps"

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: "BatchID"
          Value: "DevOps"

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubNet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZone1
      MapPublicIpOnLaunch: true
      CidrBlock: !Ref PublicSubnetCidr
      VpcId: !Ref VPC
      Tags:
        - Key: "BatchID"
          Value: "DevOps"

  PrivateSubNet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZone1
      CidrBlock: !Ref PrivateSubnetCidr
      VpcId: !Ref VPC
      Tags:
        - Key: "BatchID"
          Value: "DevOps"


  PrivateDBSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZone2
      CidrBlock: !Ref PrivateDBSubnetCidr
      VpcId: !Ref VPC
      Tags:
        - Key: "BatchID"
          Value: "DevOps"

    #  AuroraDBCluster:
    #    Type: 'AWS::RDS::DBCluster'
    #    Properties: 
    #      BackupRetentionPeriod: !Ref BackupRetentionPeriod
    #      DBClusterIdentifier: !Sub '${DatabaseName}-${AuroraEngine}-cluster'
    #      DatabaseName: !Ref DatabaseName
    #      DBSubnetGroupName: !Ref DBSubnetGroup
    #      DBClusterParameterGroupName: !Ref ClusterParameterGroup
    #      DeletionProtection: true
    #      EnableCloudwatchLogsExports: 
    #        - 'error'
    #        - 'audit'
    #      EnableIAMDatabaseAuthentication: !Ref EnableIAMDatabaseAuthentication
    #      Engine: !Ref AuroraEngine
    #      EngineMode: 'provisioned'
    #      EngineVersion: !Ref EngineVersion
    #      KmsKeyId: !Ref DatabaseKMSKey
    #      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref MasterUser, '}}' ]]
    #      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref MasterPassword, '}}' ]]
    #      Port: !Ref DBPort
    #      PreferredBackupWindow: !Ref BackupWindow
    #      PreferredMaintenanceWindow: !Ref MaintenanceWindow
    #      StorageEncrypted: true
    #      VpcSecurityGroupIds: 
    #      - !Ref SecurityGroupDatabase



Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - AngularVoteApp
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - AngularVoteApp
          - DomainName
    Description: Name of S3 bucket to hold website content
