pipeline {
    agent any
    environment {
       DOCKER_OUT = 'mequam/django-vote-v1'
       DOCKER_CREDS_ID = 'docker'
    }
    stages {
        stage('Clone Repo') {
            steps {
               checkout scm
            }
        }
        stage('Build') {
            steps {
                script {
                   dockerImage = docker.build(DOCKER_OUT,"./api")
                }
            }
        }
        stage('Push Image') {
           steps {
               script {
                  docker.withRegistry('',DOCKER_CREDS_ID) {
                     dockerImage.push()
                  }
               }
           }
        }
    }
}
