name: Vote Docker Build
on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: cd ./api
      run: docker build . --file Dockerfile --tag mequam/django-vote-pipeline
