name: API Build
on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: ./api
      run: docker build . --file Dockerfile --tag mequam/django-vote-pipeline

    # You may pin to the exact commit or the version.
    # uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
    - name: push docker image
      uses: docker/login-action@v3.3.0
      with:
        # Username used to log against the Docker registry
        username: ${{ variables.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
            
